{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datname",
    "query": {
     "query": "label_values(pg_stat_database_blks_hit,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " Uptime ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"postgres_exporter\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  rate(pg_stat_database_blks_hit{job=\"postgres_exporter\", datname=\"gauteng_db\"}[5m])\n  /\n  (\n    rate(pg_stat_database_blks_hit{job=\"postgres_exporter\", datname=\"gauteng_db\"}[5m])\n    + rate(pg_stat_database_blks_read{job=\"postgres_exporter\", datname=\"gauteng_db\"}[5m])\n  )\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples read/sec",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{job=\"postgres_exporter\", datname=\"gauteng_db\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits vs Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{job=\"postgres_exporter\", datname=\"gauteng_db\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{job=\"postgres_exporter\", datname=\"$datname\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Commits ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{job=\"postgres_exporter\", datname=\"$datname\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Transactions per second (QPS) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{job=\"postgres_exporter\", datname=\"$datname\"}[5m])\n+\nrate(pg_stat_database_xact_rollback{job=\"postgres_exporter\", datname=\"$datname\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB size in MB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"postgres_exporter\", datname=\"$datname\"} / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections by state ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{job=\"postgres_exporter\", datname=\"$datname\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=\"postgres_exporter\", datname=\"$datname\"})\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}