{
 "title": "Node exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   { "name": "window", "query": "1m,10m,30m,1h" },
   {
    "name": "mountpoint",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{instance=\"$node\", fstype!~\"tmpfs|overlay\"},mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network out",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_bytes_total{\n    job=\"node_exporter\",\n    instance=\"$node\",\n    device!~\"lo\"\n  }[$window])\n) * 8 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_receive_bytes_total{\n    job=\"node_exporter\",\n    instance=\"$node\",\n    device!~\"lo\"\n  }[$window])\n) * 8 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  node_time_seconds{job=\"node_exporter\", instance=\"$node\"}\n- node_boot_time_seconds{job=\"node_exporter\", instance=\"$node\"}\n) / 3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - (\n  rate(node_cpu_seconds_total{\n    job=\"node_exporter\",\n    instance=\"$node\",\n    mode=\"idle\"\n  }[$window]) * 100\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Disk Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  node_filesystem_avail_bytes{\n    job=\"node_exporter\",\n    instance=\"$node\",\n    fstype!~\"tmpfs|overlay\",\n    mountpoint=~\"$mountpoint\"\n  }\n  /\n  node_filesystem_size_bytes{\n    job=\"node_exporter\",\n    instance=\"$node\",\n    fstype!~\"tmpfs|overlay\",\n    mountpoint=~\"$mountpoint\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage (%) ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n  node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"$node\"}\n- node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"$node\"}\n)\n/\nnode_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"$node\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Used memory (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"$node\"}\n- node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"$node\"}\n) / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Total memory (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"$node\"}\n  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average 1 / 5 / 15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "node_load15{job=\"node_exporter\", instance=\"$node\"}\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 - (\n  rate(node_cpu_seconds_total{\n    job=\"node_exporter\",\n    instance=\"$node\",\n    mode=\"idle\"\n  }[$window]) * 100\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU usage (%) ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance) (\n    rate(node_cpu_seconds_total{\n      job=\"node_exporter\",\n      instance=\"$node\",\n      mode=\"idle\"\n    }[$window])\n  ) * 100\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}